/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"


void
calculadora_1(char *host, int a, char operador, int b)
{
	CLIENT *clnt;
	calc_resultado  *result_1;
	operandos mis_operandos;
		mis_operandos.a = a;
		mis_operandos.b = b;

	xdr_free((xdrproc_t)xdr_calc_resultado, &result_1);


#ifndef	DEBUG
	clnt = clnt_create (host, CALCULADORA, CALC_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

switch (operador) {
	case '+':
		result_1 = suma_1(mis_operandos, clnt);
		printf("%d + %d = %d\n", mis_operandos.a, mis_operandos.b, result_1->calc_resultado_u.resultado);
	break;

	case '-':
		result_1 = resta_1(mis_operandos, clnt);
		printf("%d - %d = %d\n", mis_operandos.a, mis_operandos.b, result_1->calc_resultado_u.resultado);
	break;

	case 'x':
		result_1 = multiplicacion_1(mis_operandos, clnt);
		printf("%d * %d = %d\n", mis_operandos.a, mis_operandos.b, result_1->calc_resultado_u.resultado);
	break;

	case '/':
		result_1 = division_1(mis_operandos, clnt);
		printf("%d / %d = %d\n", mis_operandos.a, mis_operandos.b, result_1->calc_resultado_u.resultado);
	break;
}

if (result_1 == (calc_resultado *) NULL) {
	clnt_perror (clnt, "call failed");
}

xdr_free((xdrproc_t)xdr_calc_resultado, result_1);

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	int a, b;
	char mi_operador;

	if (argc != 5) {
		printf ("usage: %s server_host a [operator] b \n", argv[0]);
			printf ("\tSuma: +");
			printf ("\tResta: -");
			printf ("\tMultiplicacion: x");
			printf ("\tDivision simple: /");
		exit (1);
	}

	host = argv[1];
	a = atoi(argv[2]);
	mi_operador = *argv[3];
	b = atoi(argv[4]);


	calculadora_1 (host, a, mi_operador, b);
exit (0);
}
